// Generated by gencpp from file detection_msgs/CropImages.msg
// DO NOT EDIT!


#ifndef DETECTION_MSGS_MESSAGE_CROPIMAGES_H
#define DETECTION_MSGS_MESSAGE_CROPIMAGES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Image.h>
#include <detection_msgs/BoundingBox.h>

namespace detection_msgs
{
template <class ContainerAllocator>
struct CropImages_
{
  typedef CropImages_<ContainerAllocator> Type;

  CropImages_()
    : image()
    , bounds()  {
    }
  CropImages_(const ContainerAllocator& _alloc)
    : image(_alloc)
    , bounds(_alloc)  {
  (void)_alloc;
    }



   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _image_type;
  _image_type image;

   typedef std::vector< ::detection_msgs::BoundingBox_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::detection_msgs::BoundingBox_<ContainerAllocator> >::other >  _bounds_type;
  _bounds_type bounds;





  typedef boost::shared_ptr< ::detection_msgs::CropImages_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::detection_msgs::CropImages_<ContainerAllocator> const> ConstPtr;

}; // struct CropImages_

typedef ::detection_msgs::CropImages_<std::allocator<void> > CropImages;

typedef boost::shared_ptr< ::detection_msgs::CropImages > CropImagesPtr;
typedef boost::shared_ptr< ::detection_msgs::CropImages const> CropImagesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::detection_msgs::CropImages_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::detection_msgs::CropImages_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::detection_msgs::CropImages_<ContainerAllocator1> & lhs, const ::detection_msgs::CropImages_<ContainerAllocator2> & rhs)
{
  return lhs.image == rhs.image &&
    lhs.bounds == rhs.bounds;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::detection_msgs::CropImages_<ContainerAllocator1> & lhs, const ::detection_msgs::CropImages_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace detection_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::detection_msgs::CropImages_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::detection_msgs::CropImages_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::detection_msgs::CropImages_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::detection_msgs::CropImages_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detection_msgs::CropImages_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detection_msgs::CropImages_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::detection_msgs::CropImages_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e90b5ef89c1ae9228a2d0f4a892eff2f";
  }

  static const char* value(const ::detection_msgs::CropImages_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe90b5ef89c1ae922ULL;
  static const uint64_t static_value2 = 0x8a2d0f4a892eff2fULL;
};

template<class ContainerAllocator>
struct DataType< ::detection_msgs::CropImages_<ContainerAllocator> >
{
  static const char* value()
  {
    return "detection_msgs/CropImages";
  }

  static const char* value(const ::detection_msgs::CropImages_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::detection_msgs::CropImages_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs/Image image\n"
"BoundingBox[]     bounds\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: detection_msgs/BoundingBox\n"
"# Copyright (c) 2017, Marko Bjelonic, Robotic Systems Lab, ETH Zurich\n"
"# All rights reserved.\n"
"\n"
"# Redistribution and use in source and binary forms, with or without\n"
"# modification, are permitted provided that the following conditions are met:\n"
"#     * Redistributions of source code must retain the above copyright\n"
"#       notice, this list of conditions and the following disclaimer.\n"
"#     * Redistributions in binary form must reproduce the above copyright\n"
"#       notice, this list of conditions and the following disclaimer in the\n"
"#       documentation and/or other materials provided with the distribution.\n"
"#     * Neither the name of the copyright holder nor the names of its\n"
"#       contributors may be used to endorse or promote products derived\n"
"#       from this software without specific prior written permission.\n"
"\n"
"# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS IS\" AND\n"
"# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED\n"
"# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE\n"
"# DISCLAIMED. IN NO EVENT SHALL COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY\n"
"# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES\n"
"# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;\n"
"# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND\n"
"# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT\n"
"# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS\n"
"# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n"
"\n"
"string Class\n"
"float64 probability\n"
"int64 xmin\n"
"int64 ymin\n"
"int64 xmax\n"
"int64 ymax\n"
;
  }

  static const char* value(const ::detection_msgs::CropImages_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::detection_msgs::CropImages_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.image);
      stream.next(m.bounds);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CropImages_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::detection_msgs::CropImages_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::detection_msgs::CropImages_<ContainerAllocator>& v)
  {
    s << indent << "image: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.image);
    s << indent << "bounds[]" << std::endl;
    for (size_t i = 0; i < v.bounds.size(); ++i)
    {
      s << indent << "  bounds[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::detection_msgs::BoundingBox_<ContainerAllocator> >::stream(s, indent + "    ", v.bounds[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DETECTION_MSGS_MESSAGE_CROPIMAGES_H
